config/routes.rb
Nmichalski::Application.routes.draw do
  
  root :to => 'application#home'

  match 'tribune' => 'application#tribune', :as => :tribune
  match 'enova' => 'application#enova', :as => :enova

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def home
  end

  def tribune
  end

  def enova
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/enova.html.erb
Enova Stuff

app/views/application/home.html.erb
<div id="content-wrap">
	<h2>Nicholas <span>Michalski</span></h2>
	<h3>Software Engineer</h3>
	<p>I am a software engineering professional with a focus on new technologies that improve business processes.</p>
	<p>I strive to use my technical and interpersonal skills to achieve goals and beat out competitors.</p>
	<div id="action-buttons">
		<a href="https://github.com/nmichalski" id="github"></a>
		<a href="https://www.linkedin.com/in/nmichalski" id="linkedin"></a>
		<a href="mailto:nicholas.a.michalski@gmail.com" id="contact"></a>
	</div>
	<div id="tooltips">
		<img id="tt-github" src="<%= image_path('tooltip_github.png') %>"/>
		<img id="tt-linkedin" src="<%= image_path('tooltip_linkedin.png') %>"/>
		<img id="tt-contact" src="<%= image_path('tooltip_contact.png') %>"/>
	</div>
</div>

<div id="slider">
	<div id="slides">
		<ul class="bxslider" style="list-style: none outside none;padding:0px !important;">
			<li><a href="<%= enova_path %>"><img src="<%= image_path('enova/enova_thumb.png') %>"/></a></li>
			<li><a href="<%= tribune_path %>"><img src="<%= image_path('tribune/tribune_thumb.png') %>"/></a></li>
		</ul>
	</div>
</div>

app/views/application/tribune.html.erb
Trib stuff.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

	<title>Nicholas Michalski | Software Engineer</title>

	<!-- OPEN SANS GOOGLE WEBFONT -->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
	<!-- NORMALIZE.CSS BROWSER STYLING NORMALIZATION -->
	<link rel="stylesheet" href="http://necolas.github.io/normalize.css/2.1.2/normalize.css">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag 	 "jquery.bxslider" %>
  <%= javascript_include_tag "application", "jquery.bxslider.min" %>
  <%= csrf_meta_tags %>

</head>
<body>

	<img src="<%= image_path('bg.jpg') %>" alt="" id="background" />

	<div id="maincontent">
		<div id="wrapper">
			<%= yield %>
		</div>
	</div>
	
</body>
</html>